name: Xiaomi-AX3000T-FIP-hanwckf

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      ssh:
        description: SSH connection to Actions
        required: false
        default: "false"

env:
  REPO_URL: https://github.com/Tony91590/bl-mt798x
  REPO_BRANCH: test_2023
  REPO_COMMIT: 
  DIY_P_SH: diy-part.sh
  SSH_ACTIONS: false
  UPLOAD_FIRMWARE: true
  UPLOAD_RELEASE: true
  TZ: Europe/Paris

  OPENWRT_NAME: hanwckf
  DEVICE_NAME: xiaomi_ax3000t-fip

permissions:
  contents: write
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Initialiser l'environnement
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /opt/ghc

          sudo apt-get update

          sudo apt-get install -y \
            build-essential \
            clang \
            flex \
            bison \
            gawk \
            gcc \
            g++ \
            gcc-aarch64-linux-gnu \
            gettext \
            git \
            libncurses-dev \
            libssl-dev \
            python3 \
            python3-pip \
            python3-setuptools \
            rsync \
            unzip \
            zlib1g-dev \
            file \
            wget \
            curl \
            xz-utils \
            cpio \
            bc \
            libelf-dev \
            device-tree-compiler

          echo "CROSS_COMPILE=aarch64-linux-gnu-" >> $GITHUB_ENV

          sudo apt-get autoremove -y
          sudo apt-get clean

          sudo timedatectl set-timezone "$TZ"

          sudo mkdir -p /workdir
          sudo chown -R $USER:$USER /workdir

      - name: Télécharger les sources U-Boot
        working-directory: /workdir
        run: |
         df -hT $PWD
         git clone $REPO_URL -b $REPO_BRANCH openwrt
         cd openwrt
        
         if [ -n "$REPO_COMMIT" ]; then
           echo "Checkout commit $REPO_COMMIT"
           git checkout "$REPO_COMMIT"
         else
          echo "Using branch $REPO_BRANCH"
         fi
        
         ln -sf /workdir/openwrt $GITHUB_WORKSPACE/openwrt

      - name: Charger le script DIY
        run: |
          chmod +x $DIY_P_SH
          cd openwrt
          $GITHUB_WORKSPACE/$DIY_P_SH
          
      - name: SSH Actions
        uses: P3TERX/ssh2actions@v1.0.0
        if: (github.event.inputs.ssh == 'true' && github.event.inputs.ssh != 'false') || contains(github.event.action, 'ssh')
        env:
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}

      - name: Compiler U-Boot
        id: compile
        run: |
          set -e

          cd openwrt

          echo "Compilation avec $(nproc) threads"

          SOC=mt7981 \
          BOARD=ax3000t \
          MULTI_LAYOUT=1 \
          FIXED_MTDPARTS=1 \
          ./build.sh

          echo "FILE_DATE=$(date +"%Y.%m.%d-%H%M")" >> $GITHUB_ENV
          echo "status=success" >> $GITHUB_OUTPUT

      - name: Vérifier l'espace disque
        if: (!cancelled())
        run: df -hT

      - name: Préparer les fichiers
        id: organize
        if: env.UPLOAD_FIRMWARE == 'true' && !cancelled()
        run: |
          test -d openwrt/output

          cd openwrt/output

          echo "FIRMWARE=$PWD" >> $GITHUB_ENV
          echo "status=success" >> $GITHUB_OUTPUT

      - name: Upload Artifact
        uses: actions/upload-artifact@v6
        if: steps.organize.outputs.status == 'success' && !cancelled()
        with:
          name: ${{ env.FILE_DATE }}-${{ env.OPENWRT_NAME }}-${{ env.DEVICE_NAME }}
          path: ${{ env.FIRMWARE }}

      - name: Créer le tag Release
        id: tag
        if: env.UPLOAD_RELEASE == 'true' && !cancelled()
        run: |
          echo "release_tag=${{ env.FILE_DATE }}-${{ env.OPENWRT_NAME }}-${{ env.DEVICE_NAME }}" >> $GITHUB_OUTPUT

          cat > release.txt << EOF
          xiaomi AX3000T FIP U-Boot

          Date de compilation :
          ${{ env.FILE_DATE }}

          Dépôt source :
          https://github.com/hanwckf/bl-mt798x

          Appareil :
          Xiaomi AX3000T

          Merci à hanwckf et à tous les contributeurs OpenWrt.
          EOF

          echo "status=success" >> $GITHUB_OUTPUT

      - name: Publier la Release GitHub
        uses: softprops/action-gh-release@v3
        if: steps.tag.outputs.status == 'success' && !cancelled()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: ${{ env.FIRMWARE }}/*
          tag_name: ${{ steps.tag.outputs.release_tag }}
          name: ${{ env.FILE_DATE }}-${{ env.OPENWRT_NAME }}-${{ env.DEVICE_NAME }}
          body_path: release.txt
